name: Build and Deploy

on:
  push:
    branches:
      - main # Adjust this to the branch you want to trigger the action

jobs:
  build_client:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push client Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          cd client
          docker build -t seancasey94/budgeter/client:latest ./budgeter
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push seancasey94/budgeter/client:latest

  build_server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push server Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          cd server
          docker build -t seancasey94/budgeter/server:latest .
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push push seancasey94/budgeter/server:latest

  deploy_client:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy client to AKS client pod
        run: |
          # Add your deployment steps here for deploying the client to S3 and invalidating CloudFront cache

  deploy_server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy server to AKS server pod
        run: |
          # Add your deployment steps here for deploying the server to AWS ECS
